Create database PokemonXS;

use PokemonXS;

CREATE TABLE usuarios (
    idUsuario INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    dtNasc DATE NOT NULL,
    genero VARCHAR(10) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha CHAR(20) NOT NULL
);

-- Criação da tabela "pokemons"
CREATE TABLE pokemons (
    idPokemons INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    qtdCurtidas INT DEFAULT 0
);

-- Criação da tabela de votos
CREATE TABLE curtidas (
    fk_usuarios INT,
    fk_pokemons INT,
    PRIMARY KEY (fk_usuarios, fk_pokemons),
    FOREIGN KEY (fk_usuarios) REFERENCES usuarios(idUsuario),
    FOREIGN KEY (fk_pokemons) REFERENCES pokemons(idPokemons)
);

CREATE TABLE Audio(
fk_pokemon int primary key auto_increment,
FOREIGN KEY (fk_pokemon) REFERENCES Pokemons(idPokemons),
    CONSTRAINT unico_audio UNIQUE (fk_pokemon),
nome varchar(50),
pagina int
);

select * from Audio;

drop table Usuarios;
drop table Pokemons;
drop table Curtidas;
drop table Audio;

INSERT INTO Usuarios VALUES
(null, 'Cauã Ribeiro Bonfim','2004-05-06','Masculino','caua@gmail.com','Caua39014646');

INSERT INTO Curtidas VALUES
(1,1);

INSERT INTO Pokemons VALUES
(null, 'Pantheon', 'Sombrio', 283),
(null, 'Pantheleon', 'Sombrio', 159),
(null, 'Panthelord', 'Sombrio', 198),
(null, 'Erukilava', 'Fogo', 72),
(null, 'Mandralava', 'Fogo', 189),
(null, 'Cinccilava', 'Fogo/Dragão', 891),
(null, 'Bufo', 'Planta', 43),
(null, 'Regulari', 'Planta', 56),
(null, 'Buforegulari', 'Planta', 18),
(null, 'Kapi', 'Água', 698),
(null, 'Capivara', 'Água', 426),
(null, 'Capivarias', 'Água', 567),
(null, 'Goli', 'Pedra', 54),
(null, 'Golemita', 'Pedra', 21),
(null, 'Golem-de-Nióbio', 'Pedra', 37),
(null, 'Plantacco', 'Planta', 45),
(null, 'Cannabola', 'Planta/Psíquico', 88),
(null, 'Cannabright', 'Planta/Psíquico', 127),
(null, 'Blu', 'Voador', 91),
(null, 'Zarara', 'Voador', 123),
(null, 'Mordecai', 'Voador', 43),
(null, 'Turguiti', 'Água', 13),
(null, 'Turtilion', 'Água', 17),
(null, 'Aquatron', 'Água', 334),
(null, 'Tuca', 'Voador', 37),
(null, 'Tucanon', 'Voador', 12),
(null, 'Titi', 'Normal/Veneno', 56),
(null, 'Lepto', 'Normal/Veneno', 75),
(null, 'Oneevil', 'Elétrico', 13),
(null, 'Antient', 'Normal', 66),
(null, 'Antienne', 'Normal', 68),
(null, 'Antiox', 'Normal', 89),
(null, 'Azumi', 'Água', 23),
(null, 'Azumar', 'Água', 43),
(null, 'Azumarilion', 'Água', 54),
(null, 'Bizori', 'Inseto', 13),
(null, 'Bizu', 'Inseto', 45),
(null, 'Bizz', 'Inseto', 54),
(null, 'Angelwool', 'Fada', 64),
(null, 'Favelha', 'Fada', 56),
(null, 'Draco', 'Dragão/Sombrio', 257),
(null, 'Draconight', 'Dragão/Sombrio', 891),
(null, 'Botozul', 'Água', 45),
(null, 'Botoshark', 'Água', 121),
(null, 'Botolodon', 'Água/Dragão', 157),
(null, 'Denguelarva', 'Inseto', 12),
(null, 'Chicungunyat', 'Inseto', 23),
(null, 'Zikatron', 'Inseto/Metal', 35),
(null, 'Yudi', 'Psíquico', 43),
(null, 'Mestre Yudi', 'Lutador/Psíquico', 457),
(null, 'Quatino', 'Normal', 23),
(null, 'Quatizap', 'Normal', 13),
(null, 'Arirania', 'Água', 12),
(null, 'Ararenea', 'Água', 45),
(null, 'Bongo Bongo', 'Veneno/Metal', 43),
(null, 'Girestrike', 'Elétrico', 56),
(null, 'Gireletrico', 'Elétrico', 76),
(null, 'Casosaur', 'Voador/Lutador', 74),
(null, 'Casosaurus', 'Voador/Lutador', 23),
(null, 'Pikazul', 'Elétrico', 533),
(null, 'Caipix', 'Fogo', 135),
(null, 'Campori', 'Fogo', 101),
(null, 'Beta', 'Água', 2),
(null, 'Sigma', 'Água', 333),
(null, 'Pedri', 'Pedra', 23),
(null, 'Pedrini', 'Pedra/Lutador', 35),
(null, 'Pedronco', 'Pedra/Lutador', 78),
(null, 'Antalus', 'Normal', 33),
(null, 'Tapyro', 'Fogo', 37),
(null, 'Ossorror', 'Fantasma', 64),
(null, 'Aquatinny', 'Água', 43),
(null, 'Aquatinna', 'Água', 32),
(null, 'Aquatindra', 'Água', 65),
(null, 'Baconius', 'Normal', 32),
(null, 'Porkchomp', 'Normal', 56),
(null, 'Skunkbloom', 'Sombrio/Planta', 23),
(null, 'Bulbix', 'Planta', 43),
(null, 'Bulbal', 'Planta', 65),
(null, 'Bulbassalto', 'Planta', 79),
(null, 'Glaciala', 'Gelo', 43),
(null, 'Cachogo', 'Fogo', 65),
(null, 'Lofogo', 'Fogo', 63),
(null, 'Lolava', 'Fogo', 79),
(null, 'Gaspar', 'Fantasma', 34),
(null, 'Gasfear', 'Fantasma', 65),
(null, 'Espectraria', 'Psíquico', 21),
(null, 'Igniberos', 'Fogo/Dragão', 56),
(null, 'Mana', 'Água', 54),
(null, 'Manati', 'Água', 78),
(null, 'Manation', 'Água', 79),
(null, 'Caramello', 'Normal', 34),
(null, 'Caramellado', 'Normal', 45),
(null, 'Caspor', 'Lutador', 65),
(null, 'Caspoeira', 'Lutador', 34),
(null, 'Swamplord', 'Terra/Veneno', 54),
(null, 'Pira', 'Água', 65),
(null, 'Pira-Pira', 'Água', 12),
(null, 'Dragonvin', 'Dragão/Planta', 54),
(null, 'Dragonsipó', 'Dragão/Planta', 45),
(null, 'Dragondoso', 'Dragão/Planta', 78),
(null, 'Mimico', 'Psíquico', 19),
(null, 'Lacrosta', 'Água', 13),
(null, 'Lacrocos', 'Água', 45),
(null, 'Croconite', 'Água/Sombrio', 49),
(null, 'Cori', 'Veneno', 89),
(null, 'Corali', 'Dragão/Veneno', 56),
(null, 'Coralion', 'Dragão/Veneno', 43),
(null, 'Chinchigode', 'Fada', 56),
(null, 'Lobito', 'Sombrio', 54),
(null, 'Lobuspidon', 'Sombrio', 470),
(null, 'Camoubush', 'Planta', 12),
(null, 'Gamber', 'Psíquico', 43),
(null, 'Gainex', 'Psíquico', 65),
(null, 'Gambolonux', 'Psíquico/Fada', 45),
(null, 'Loro', 'Voador', 43),
(null, 'José', 'Voador', 32),
(null, 'Mimaco', 'Normal', 34),
(null, 'Mamico', 'Normal', 65),
(null, 'Mamaco', 'Lutador', 76),
(null, 'Pondaor', 'Normal', 56),
(null, 'Phantasma', 'Fantasma', 23),
(null, 'Aimary', 'Água', 56),
(null, 'Aimoon', 'Gelo', 76),
(null, 'Rhymal', 'Metal', 56),
(null, 'Rhythorn', 'Metal', 34),
(null, 'Pombion', 'Voador', 56),
(null, 'Pombiot', 'Voador', 32),
(null, 'Pombiotto', 'Voador', 65),
(null, 'Sayury', 'Água/Psíquico', 23),
(null, 'Geoshark', 'Água/Pedra', 56),
(null, 'Litiodactyl', 'Pedra/Dragão', 65),
(null, 'Piuky', 'Fada/Água', 75),
(null, 'Piukynox', 'Fada/Água', 23),
(null, 'Benjamor', 'Elétrico', 65),
(null, 'Benjavarios', 'Elétrico', 71),
(null, 'Hitmanchete', 'Lutador', 43),
(null, 'Bandeirogo', 'Fogo/Voador', 34),
(null, 'Arraiatico', 'Fogo/Voador', 53),
(null, 'Pacaflora', 'Planta', 51),
(null, 'Noctowl de São Paulo', 'Voador', 10),
(null, 'Querodart', 'Voador', 54),
(null, 'Querocaos', 'Voador', 61),
(null, 'Kof Kof', 'Veneno', 35),
(null, 'Solarigator', 'Elétrico', 17),
(null, 'Sloty', 'Normal', 63),
(null, 'Slothking', 'Normal', 91),
(null, 'Meowstic', 'Fada/Dragão', 121),
(null, 'Leviatan', 'Água/Fada', 89),
(null, 'Phantasmal', 'Fantasma', 14),
(null, 'Borbosia', 'Voador/Inseto', 53),
(null, 'Metano', 'Metal', 21),
(null, 'Metanon', 'Metal', 45),
(null, 'Metalord', 'Metal', 88),
(null, 'Seabird', 'Voador/Água', 13),
(null, 'Metallica', 'Metal', 43),
(null, 'CompuGPTech', 'Elétrico', 404),
(null, 'Pastudo', 'Lutador', 157),
(null, 'Araucagélido', 'Gelo', 151),
(null, 'Tatucs', 'Terra', 23),
(null, 'Tatum', 'Terra', 54),
(null, 'Crustaconcha', 'Água', 67),
(null, 'Crustaking', 'Água', 23),
(null, 'Crustalion', 'Água', 64),
(null, 'Ariadinarak', 'Inseto', 54),
(null, 'Ariana Del Rey', 'Inseto', 76),
(null, 'Cobroca', 'Pedra', 87),
(null, 'Brocomonstro', 'Pedra', 83),
(null, 'Moojitsu', 'Normal/Lutador', 17),
(null, 'Mooaythai', 'Normal/Lutador', 75),
(null, 'Aquaraptor', 'Água', 53),
(null, 'Furton', 'Lutador', 36),
(null, 'Guaramite', 'Planta', 74),
(null, 'Guaradião', 'Planta', 65),
(null, 'Gaille', 'Lutador', 32),
(null, 'Gallos', 'Lutador', 54),
(null, 'Rocktorr', 'Pedra', 65),
(null, 'Electrobola', 'Elétrico', 32),
(null, 'Voltobola', 'Elétrico', 53),
(null, 'Colotinho', 'Normal', 331),
(null, 'Tourogo', 'Fogo/Elétrico', 43),
(null, 'Flamullyn', 'Fogo', 34),
(null, 'Mozilla', 'Fogo', 65),
(null, 'Firefox', 'Fogo', 71),
(null, 'Loirinea', 'Fantasma', 34),
(null, 'Godzalla', 'Dragão', 44),
(null, 'Nymphiara', 'Água', 124),
(null, 'Botorosa', 'Água', 127),
(null, 'Cerberontres', 'Fogo', 255),
(null, 'Espiritauls', 'Fantasma', 241),
(null, 'Polimacho', 'Lutador', 54),
(null, 'Nebulost', 'Metal', 277),
(null, 'Necrofox', 'Sombrio', 213),
(null, 'Verdecaos', 'Planta', 155),
(null, 'Harpycuno', 'Voador', 53),
(null, 'Mantialos', 'Água', 631),
(null, 'Kurupasso', 'Planta', 53),
(null, 'Tornasci', 'Terra', 132),
(null, 'Nyxtwo', 'Psíquico', 433),
(null, 'Zephy', 'Voador', 54),
(null, 'Solaris', 'Desconhecido', 735);

insert into Audio values
(null, 'audio1', 1),
(null, 'audio2', 1),
(null, 'audio3', 1),
(null, 'audio4', 1),
(null, 'audio5', 1),
(null, 'audio6', 1),
(null, 'audio7', 1),
(null, 'audio8', 1),
(null, 'audio9', 1),
(null, 'audio10', 1),
(null, 'audio11', 1),
(null, 'audio12', 1),
(null, 'audio13', 1),
(null, 'audio14', 1),
(null, 'audio15', 1),
(null, 'audio16', 1),
(null, 'audio17', 1),
(null, 'audio18', 1),
(null, 'audio19', 1),
(null, 'audio20', 1),
(null, 'audio21', 1),
(null, 'audio22', 1),
(null, 'audio23', 1),
(null, 'audio24', 1),
(null, 'audio25', 1),
(null, 'audio26', 1),
(null, 'audio27', 1),
(null, 'audio28', 1),
(null, 'audio29', 1),
(null, 'audio30', 1),
(null, 'audio31', 1),
(null, 'audio32', 1),
(null, 'audio33', 1),
(null, 'audio34', 1),
(null, 'audio35', 1),
(null, 'audio36', 1),
(null, 'audio37', 1),
(null, 'audio38', 1),
(null, 'audio39', 1),
(null, 'audio40', 1),
(null, 'audio41', 1),
(null, 'audio42', 1),
(null, 'audio43', 1),
(null, 'audio44', 1),
(null, 'audio45', 1),
(null, 'audio46', 1),
(null, 'audio47', 1),
(null, 'audio48', 1),
(null, 'audio49', 1),
(null, 'audio50', 1),
(null, 'audio1', 2),
(null, 'audio2', 2),
(null, 'audio3', 2),
(null, 'audio4', 2),
(null, 'audio5', 2),
(null, 'audio6', 2),
(null, 'audio7', 2),
(null, 'audio8', 2),
(null, 'audio9', 2),
(null, 'audio10', 2),
(null, 'audio11', 2),
(null, 'audio12', 2),
(null, 'audio13', 2),
(null, 'audio14', 2),
(null, 'audio15', 2),
(null, 'audio16', 2),
(null, 'audio17', 2),
(null, 'audio18', 2),
(null, 'audio19', 2),
(null, 'audio20', 2),
(null, 'audio21', 2),
(null, 'audio22', 2),
(null, 'audio23', 2),
(null, 'audio24', 2),
(null, 'audio25', 2),
(null, 'audio26', 2),
(null, 'audio27', 2),
(null, 'audio28', 2),
(null, 'audio29', 2),
(null, 'audio30', 2),
(null, 'audio31', 2),
(null, 'audio32', 2),
(null, 'audio33', 2),
(null, 'audio34', 2),
(null, 'audio35', 2),
(null, 'audio36', 2),
(null, 'audio37', 2),
(null, 'audio38', 2),
(null, 'audio39', 2),
(null, 'audio40', 2),
(null, 'audio41', 2),
(null, 'audio42', 2),
(null, 'audio43', 2),
(null, 'audio44', 2),
(null, 'audio45', 2),
(null, 'audio46', 2),
(null, 'audio47', 2),
(null, 'audio48', 2),
(null, 'audio49', 2),
(null, 'audio50', 2),
(null, 'audio1', 3),
(null, 'audio2', 3),
(null, 'audio3', 3),
(null, 'audio4', 3),
(null, 'audio5', 3),
(null, 'audio6', 3),
(null, 'audio7', 3),
(null, 'audio8', 3),
(null, 'audio9', 3),
(null, 'audio10', 3),
(null, 'audio11', 3),
(null, 'audio12', 3),
(null, 'audio13', 3),
(null, 'audio14', 3),
(null, 'audio15', 3),
(null, 'audio16', 3),
(null, 'audio17', 3),
(null, 'audio18', 3),
(null, 'audio19', 3),
(null, 'audio20', 3),
(null, 'audio21', 3),
(null, 'audio22', 3),
(null, 'audio23', 3),
(null, 'audio24', 3),
(null, 'audio25', 3),
(null, 'audio26', 3),
(null, 'audio27', 3),
(null, 'audio28', 3),
(null, 'audio29', 3),
(null, 'audio30', 3),
(null, 'audio31', 3),
(null, 'audio32', 3),
(null, 'audio33', 3),
(null, 'audio34', 3),
(null, 'audio35', 3),
(null, 'audio36', 3),
(null, 'audio37', 3),
(null, 'audio38', 3),
(null, 'audio39', 3),
(null, 'audio40', 3),
(null, 'audio41', 3),
(null, 'audio42', 3),
(null, 'audio43', 3),
(null, 'audio44', 3),
(null, 'audio45', 3),
(null, 'audio46', 3),
(null, 'audio47', 3),
(null, 'audio48', 3),
(null, 'audio49', 3),
(null, 'audio50', 3),
(null, 'audio1', 4),
(null, 'audio2', 4),
(null, 'audio3', 4),
(null, 'audio4', 4),
(null, 'audio5', 4),
(null, 'audio6', 4),
(null, 'audio7', 4),
(null, 'audio8', 4),
(null, 'audio9', 4),
(null, 'audio10', 4),
(null, 'audio11', 4),
(null, 'audio12', 4),
(null, 'audio13', 4),
(null, 'audio14', 4),
(null, 'audio15', 4),
(null, 'audio16', 4),
(null, 'audio17', 4),
(null, 'audio18', 4),
(null, 'audio19', 4),
(null, 'audio20', 4),
(null, 'audio21', 4),
(null, 'audio22', 4),
(null, 'audio23', 4),
(null, 'audio24', 4),
(null, 'audio25', 4),
(null, 'audio26', 4),
(null, 'audio27', 4),
(null, 'audio28', 4),
(null, 'audio29', 4),
(null, 'audio30', 4),
(null, 'audio31', 4),
(null, 'audio32', 4),
(null, 'audio33', 4),
(null, 'audio34', 4),
(null, 'audio35', 4),
(null, 'audio36', 4),
(null, 'audio37', 4),
(null, 'audio38', 4),
(null, 'audio39', 4),
(null, 'audio40', 4),
(null, 'audio41', 4),
(null, 'audio42', 4),
(null, 'audio43', 4),
(null, 'audio44', 4),
(null, 'audio45', 4),
(null, 'audio46', 4),
(null, 'audio47', 4),
(null, 'audio48', 4),
(null, 'audio49', 4),
(null, 'audio50', 4);

truncate table Pokemons;

select * from Usuarios;
select idUsuario from usuarios where email = 'a';
select idUsuario from usuarios where email = 'a';
insert into curtidas values ((select idUsuario from usuarios where email = 'a'), 1);
select * from Pokemons;
select * from Curtidas;

delete from Curtidas where fk_usuarios = (select idUsuario from usuarios where email = 'a') and fk_pokemons = 34;
truncate table Curtidas;
select * from Comentarios;
select nome, qtdCurtidas from Pokemons order by qtdCurtidas desc limit 5;
update Pokemons
SET qtdCurtidas = qtdCurtidas + 1
WHERE idPokemons = 12;


update Pokemons
SET qtdCurtidas = qtdCurtidas - 1
WHERE idPokemons = 34;